export const screens = {
  // Auth stack
  AUTH_AUTHENTIFICATION: 'AUTH_AUTHENTIFICATION',
  AUTH_CONFARMATION: 'AUTH_CONFARMATION',
  // Auth stack

  // App stack
  MAIN_APP: 'MAIN_APP',
  //

  // TABS
  CHAT_TAB: 'CHAT_TAB',
  CALL_TAB: 'CALL_TAB',
  EXPLORE_TAB: 'EXPLORE_TAB',
  SETTINGS_TAB: 'SETTINGS_TAB',
  // TABS

  //  CHAT_STACK
  CHAT_MAIN: 'CHAT_MAIN',
  CHAT_DETAIL: 'CHAT_DETAIL',
  //  CHAT_STACKS

  //CALL_TAB
  CALL_MAIN: 'CALL_MAIN',
  //CALL_TAB

  //EXPLORE_TAB
  EXPLORE_MAIN: 'EXPLORE_MAIN',
  //EXPLORE_TAB

  //SETTINGS_TAB
  SETTINGS_MAIN: 'SETTINGS_MAIN',
  //SETTINGS_TAB
};
